name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: actions/checkout@v4
      - uses: bats-core/bats-action@3.0.1
        with:
          support-path: /usr/lib/bats/bats-support
          assert-path: /usr/lib/bats/bats-assert
      - run: bats --recursive test
