name: Pages

on:
  push:
    branches: main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - run: gem install --user ronn-ng
      - run: |
          for bin in "$HOME/.local/share/gem/ruby"/*/bin; do
            echo "$bin" >>"$GITHUB_PATH"
          done
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5

      - name: Generate HTML man-pages
        run: ronn --style toc,custom --html man/*.ronn
        env:
          RONN_STYLE: ./man

      - name: Copy HTML sources to _site
        run: |
          mkdir -p _site
          cp -v man/*.html _site/
          cp -v _site/aws-ssm-rename.1.html _site/index.html

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      - id: deployment
        uses: actions/deploy-pages@v4
